#ifndef __IEEE80211_EXTERNAL_CONFIG__H
#define __IEEE80211_EXTERNAL_CONFIG__H
#ifndef DIRECT_ATTACH
#define DIRECT_ATTACH
#endif
#ifndef ATH_AHB
#define ATH_AHB
#endif
#ifndef ATH_PCI
#define ATH_PCI
#endif
#ifndef AH_CAL_IN_FILE_HOST
#define AH_CAL_IN_FILE_HOST 1
#endif
#ifndef CALDATA0_FILE_PATH
#define CALDATA0_FILE_PATH "/tmp/wifi0.caldata"
#endif
#ifndef CALDATA1_FILE_PATH
#define CALDATA1_FILE_PATH "/tmp/wifi1.caldata"
#endif
#ifndef CALDATA2_FILE_PATH
#define CALDATA2_FILE_PATH "/tmp/wifi2.caldata"
#endif



#ifndef __LINUX_ARM_ARCH__
#define __LINUX_ARM_ARCH__ 7
#endif






#ifndef AH_BYTE_ORDER
#define AH_BYTE_ORDER AH_LITTLE_ENDIAN
#endif















#ifndef HOST_SW_TSO_ENABLE
#define HOST_SW_TSO_ENABLE 0
#endif
#ifndef HOST_SW_TSO_SG_ENABLE
#define HOST_SW_TSO_SG_ENABLE 1
#endif
#ifndef HOST_SW_SG_ENABLE
#define HOST_SW_SG_ENABLE 1
#endif
#ifndef HOST_SW_LRO_ENABLE
#define HOST_SW_LRO_ENABLE 1
#endif
#ifndef QCA_OL_GRO_ENABLE
#define QCA_OL_GRO_ENABLE 1
#endif
#ifndef RX_CHECKSUM_OFFLOAD
#define RX_CHECKSUM_OFFLOAD 1
#endif
#ifndef TCP_CHECKSUM_OFFLOAD
#define TCP_CHECKSUM_OFFLOAD 1
#endif
#ifndef PCI_PEREGRINE_V2_X86_WAR
#define PCI_PEREGRINE_V2_X86_WAR 0
#endif
#ifndef ATH_OL_FAST_CHANNEL_RESET_WAR
#define ATH_OL_FAST_CHANNEL_RESET_WAR 0
#endif
#ifndef OL_ATH_SUPPORT_STATS
#define OL_ATH_SUPPORT_STATS 1
#endif
#ifndef AP_MULTIPLE_BUFFER_RCV
#define AP_MULTIPLE_BUFFER_RCV 0
#endif
#ifndef ATH_SUPPORT_RX_PROC_QUOTA
#define ATH_SUPPORT_RX_PROC_QUOTA 0
#endif
#ifndef ATH_SUPPORT_CWM
#define ATH_SUPPORT_CWM 1
#endif
#ifndef ATH_SUPPORT_AGGR_BURST
#define ATH_SUPPORT_AGGR_BURST 1
#endif
#ifndef ATH_RXBUF
#define ATH_RXBUF 512
#endif
#ifndef ATH_TXBUF
#define ATH_TXBUF 2700
#endif
#ifndef ATH_SUPPORT_DFS
#define ATH_SUPPORT_DFS 1
#endif
#ifndef ATH_SUPPORT_STA_DFS
#define ATH_SUPPORT_STA_DFS 1
#endif
#ifndef ATH_SUPPORT_ZERO_CAC_DFS
#define ATH_SUPPORT_ZERO_CAC_DFS 1
#endif
#ifndef ATH_SUPPORT_SPECTRAL
#define ATH_SUPPORT_SPECTRAL 1
#endif
#ifndef ATH_SUPPORT_ICM
#define ATH_SUPPORT_ICM 1
#endif
#ifndef ATH_SUPPORT_VLAN
#define ATH_SUPPORT_VLAN 1
#endif
#ifndef ATH_AMSDU
#define ATH_AMSDU 1
#endif
#ifndef ATH_SUPPORT_UAPSD
#define ATH_SUPPORT_UAPSD 1
#endif
#ifndef ATH_SUPPORT_DESCFAST
#define ATH_SUPPORT_DESCFAST 1
#endif
#ifndef BUILD_AP
#define BUILD_AP 1
#endif
#ifndef IEEE80211_MCAST_ENHANCEMENT
#define IEEE80211_MCAST_ENHANCEMENT 1
#endif
#ifndef ATH_SUPPORT_IQUE
#define ATH_SUPPORT_IQUE 1
#endif
#ifndef ATH_SUPPORT_EXT_STAT
#define ATH_SUPPORT_EXT_STAT 1
#endif
#ifndef ATH_EXTRA_RATE_INFO_STA
#define ATH_EXTRA_RATE_INFO_STA 0
#endif
#ifndef ATH_SUPPORT_WAPI
#define ATH_SUPPORT_WAPI 1
#endif
#ifndef ATH_SUPPORT_UAPSD_RATE_CONTROL
#define ATH_SUPPORT_UAPSD_RATE_CONTROL 1
#endif
#ifndef ATH_WPS_IE
#define ATH_WPS_IE 1
#endif
#ifndef NO_SIMPLE_CONFIG
#define NO_SIMPLE_CONFIG 1
#endif
#ifndef ATH_SUPPORT_HYFI_ENHANCEMENTS
#define ATH_SUPPORT_HYFI_ENHANCEMENTS 1
#endif
#ifndef UMAC
#define UMAC
#endif
#ifndef ADF_SUPPORT
#define ADF_SUPPORT 1
#endif
#ifndef ATH_HW_TXQ_STUCK_WAR
#define ATH_HW_TXQ_STUCK_WAR 1
#endif
#ifndef ATH_SUPPORT_VOW_DCS
#define ATH_SUPPORT_VOW_DCS 1
#endif
#ifndef ATH_SUPPORT_LED
#define ATH_SUPPORT_LED 0
#endif
#ifndef OL_ATH_SUPPORT_LED
#define OL_ATH_SUPPORT_LED 1
#endif
#ifndef OL_ATH_SUPPORT_LED_POLL
#define OL_ATH_SUPPORT_LED_POLL 1
#endif
#ifndef ATH_SUPPORT_GREEN_AP
#define ATH_SUPPORT_GREEN_AP 1
#endif
#ifndef IEEE80211_USE_WPA_CCMP
#define IEEE80211_USE_WPA_CCMP 1
#endif
#ifndef ATH_EXT_AP
#define ATH_EXT_AP 1
#endif
#ifndef ATH_TX_BUF_FLOW_CNTL
#define ATH_TX_BUF_FLOW_CNTL 1
#endif
#ifndef ATH_TX_DROP_POLICY
#define ATH_TX_DROP_POLICY 1
#endif
#ifndef ATH_SUPPORT_QUICK_KICKOUT
#define ATH_SUPPORT_QUICK_KICKOUT 1
#endif
#ifndef ATH_SUPPORT_IBSS
#define ATH_SUPPORT_IBSS 1
#endif
#ifndef ATH_IBSS_DFS_CHANNEL_SUPPORT
#define ATH_IBSS_DFS_CHANNEL_SUPPORT 1
#endif
#ifndef ATH_SUPPORT_EDMA
#define ATH_SUPPORT_EDMA 1
#endif
#ifndef UMAC_SUPPORT_AP_POWERSAVE
#define UMAC_SUPPORT_AP_POWERSAVE 1
#endif
#ifndef UMAC_SUPPORT_STA_POWERSAVE
#define UMAC_SUPPORT_STA_POWERSAVE 1
#endif
#ifndef UMAC_SUPPORT_POWERSAVE_QUEUE
#define UMAC_SUPPORT_POWERSAVE_QUEUE 1
#endif
#ifndef LMAC_SUPPORT_POWERSAVE_QUEUE
#define LMAC_SUPPORT_POWERSAVE_QUEUE 1
#endif
#ifndef ATH_FRAG_TX_COMPLETE_DEFER
#define ATH_FRAG_TX_COMPLETE_DEFER 0
#endif
#ifndef UMAC_SUPPORT_CCMP_SW_CRYPTO
#define UMAC_SUPPORT_CCMP_SW_CRYPTO 1
#endif
#ifndef UMAC_SUPPORT_TKIP_SW_CRYPTO
#define UMAC_SUPPORT_TKIP_SW_CRYPTO 1
#endif
#ifndef ATH_SUPPORT_WEP_MBSSID
#define ATH_SUPPORT_WEP_MBSSID 0
#endif
#ifndef UMAC_SUPPORT_RESMGR_SM
#define UMAC_SUPPORT_RESMGR_SM 0
#endif
#ifndef UMAC_SUPPORT_RESMGR
#define UMAC_SUPPORT_RESMGR 0
#endif
#ifndef UMAC_SUPPORT_RESMGR_OC_SCHED
#define UMAC_SUPPORT_RESMGR_OC_SCHED 0
#endif
#ifndef UMAC_SUPPORT_RIJNDAEL
#define UMAC_SUPPORT_RIJNDAEL 1
#endif
#ifndef UMAC_SUPPORT_ACS
#define UMAC_SUPPORT_ACS 1
#endif
#ifndef UMAC_SUPPORT_WDS
#define UMAC_SUPPORT_WDS 1
#endif
#ifndef UMAC_SUPPORT_NAWDS
#define UMAC_SUPPORT_NAWDS 1
#endif
#ifndef UMAC_SUPPORT_STAFWD
#define UMAC_SUPPORT_STAFWD 0
#endif
#ifndef UMAC_SUPPORT_DFS
#define UMAC_SUPPORT_DFS 1
#endif
#ifndef ATH_ACL_SOFTBLOCKING
#define ATH_ACL_SOFTBLOCKING 1
#endif
#ifndef UMAC_SUPPORT_ACL
#define UMAC_SUPPORT_ACL 1
#endif
#ifndef UMAC_SUPPORT_TX_FRAG
#define UMAC_SUPPORT_TX_FRAG 1
#endif
#ifndef ATH_SUPPORT_WIFIPOS
#define ATH_SUPPORT_WIFIPOS 1
#endif
#ifndef UMAC_SUPPORT_WIFIPOS
#define UMAC_SUPPORT_WIFIPOS 1
#endif
#ifndef UMAC_SUPPORT_WIFIPOS_LEANCC
#define UMAC_SUPPORT_WIFIPOS_LEANCC 1
#endif
#ifndef ATH_SUPPORT_WIFIPOS_ONE_VAP
#define ATH_SUPPORT_WIFIPOS_ONE_VAP 1
#endif
#ifndef ATH_SUPPORT_LOWI
#define ATH_SUPPORT_LOWI 1
#endif
#ifndef UMAC_SUPPORT_IBSS
#define UMAC_SUPPORT_IBSS 1
#endif
#ifndef UMAC_REPEATER_DELAYED_BRINGUP
#define UMAC_REPEATER_DELAYED_BRINGUP 0
#endif
#ifndef ATH_SUPPORT_TxBF
#define ATH_SUPPORT_TxBF 1
#endif
#ifndef ATHEROS_LINUX_PERIODIC_SCAN
#define ATHEROS_LINUX_PERIODIC_SCAN 1
#endif
#ifndef ATHEROS_LINUX_PERIODIC_SCAN
#define ATHEROS_LINUX_PERIODIC_SCAN 1
#endif
#ifndef ATH_DEBUG
#define ATH_DEBUG 1
#endif
#ifndef UMAC_SUPPORT_VAP_PAUSE
#define UMAC_SUPPORT_VAP_PAUSE 1
#endif
#ifndef ATH_VAP_PAUSE_SUPPORT
#define ATH_VAP_PAUSE_SUPPORT 1
#endif
#ifndef ATH_SUPPORT_TX_BACKLOG
#define ATH_SUPPORT_TX_BACKLOG 1
#endif
#ifndef ATH_DEBUG
#define ATH_DEBUG 1
#endif
#ifndef ATH_SUPPORT_IBSS_HT
#define ATH_SUPPORT_IBSS_HT 1
#endif
#ifndef ATH_SUPPORT_IBSS_WMM
#define ATH_SUPPORT_IBSS_WMM 1
#endif
#ifndef ATH_SUPPORT_IBSS_NETLINK_NOTIFICATION
#define ATH_SUPPORT_IBSS_NETLINK_NOTIFICATION 1
#endif
#ifndef ATH_SUPPORT_IBSS_PRIVATE_SECURITY
#define ATH_SUPPORT_IBSS_PRIVATE_SECURITY 1
#endif
#ifndef ATH_SUPPORT_IBSS_ACS
#define ATH_SUPPORT_IBSS_ACS 1
#endif
#ifndef ATH_SUPPORT_AP_WDS_COMBO
#define ATH_SUPPORT_AP_WDS_COMBO 0
#endif
#ifndef UMAC_SUPPORT_BSSLOAD
#define UMAC_SUPPORT_BSSLOAD 1
#endif
#ifndef UMAC_SUPPORT_ADMCTL
#define UMAC_SUPPORT_ADMCTL 1
#endif
#ifndef UMAC_SUPPORT_RRM
#define UMAC_SUPPORT_RRM 1
#endif
#ifndef UMAC_SUPPORT_RRM_MISC
#define UMAC_SUPPORT_RRM_MISC 0
#endif
#ifndef UMAC_SUPPORT_RRM_DEBUG
#define UMAC_SUPPORT_RRM_DEBUG 0
#endif
#ifndef UMAC_SUPPORT_WNM
#define UMAC_SUPPORT_WNM 1
#endif
#ifndef UMAC_SUPPORT_IE_UTILS
#define UMAC_SUPPORT_IE_UTILS 1
#endif
#ifndef UMAC_SUPPORT_QUIET
#define UMAC_SUPPORT_QUIET 1
#endif
#ifndef ATH_SUPPORT_ATHVAP_INFO
#define ATH_SUPPORT_ATHVAP_INFO 0
#endif
#ifndef ATH_RXBUF_RECYCLE
#define ATH_RXBUF_RECYCLE 0
#endif
#ifndef ATH_SUPPORT_PAPRD
#define ATH_SUPPORT_PAPRD 1
#endif
#ifndef ATH_TRAFFIC_FAST_RECOVER
#define ATH_TRAFFIC_FAST_RECOVER 1
#endif
#ifndef UMAC_SUPPORT_VI_DBG
#define UMAC_SUPPORT_VI_DBG 1
#endif
#ifndef UMAC_SUPPORT_VOW_DBG
#define UMAC_SUPPORT_VOW_DBG 0
#endif
#ifndef ATH_SUPPORT_DYN_TX_CHAINMASK
#define ATH_SUPPORT_DYN_TX_CHAINMASK 1
#endif
#ifndef ATH_SUPPORT_IBSS_DFS
#define ATH_SUPPORT_IBSS_DFS 1
#endif
#ifndef ATH_SUPPORT_IBSS_DFS
#define ATH_SUPPORT_IBSS_DFS 1
#endif
#ifndef ATH_BT_COEX_3WIRE_MODE
#define ATH_BT_COEX_3WIRE_MODE 0
#endif
#ifndef ATH_SUPPORT_IBSS_PERSTA_HWKEY
#define ATH_SUPPORT_IBSS_PERSTA_HWKEY 1
#endif
#ifndef ATH_SUPPORT_IBSS_WPA2
#define ATH_SUPPORT_IBSS_WPA2 1
#endif
#ifndef ATH_SWRETRY
#define ATH_SWRETRY 1
#endif
#ifndef ATH_SUPPORT_IBSS_WPA2
#define ATH_SUPPORT_IBSS_WPA2 1
#endif
#ifndef UMAC_SUPPORT_APONLY
#define UMAC_SUPPORT_APONLY 1
#endif
#ifndef ATH_TX_COMPACT
#define ATH_TX_COMPACT 1
#endif
#ifndef QCA_OL_TX_CACHEDHDR
#define QCA_OL_TX_CACHEDHDR 1
#endif
#ifndef QCA_OL_TX_PDEV_LOCK
#define QCA_OL_TX_PDEV_LOCK 1
#endif
#ifndef ATH_SUPPORT_TIDSTUCK_WAR
#define ATH_SUPPORT_TIDSTUCK_WAR 0
#endif
#ifndef ATH_SUPPORT_DSCP_OVERRIDE
#define ATH_SUPPORT_DSCP_OVERRIDE 1
#endif
#ifndef UMAC_SUPPORT_STA_STATS
#define UMAC_SUPPORT_STA_STATS 1
#endif
#ifndef UMAC_SUPPORT_STA_STATS_ENHANCEMENT
#define UMAC_SUPPORT_STA_STATS_ENHANCEMENT 1
#endif
#ifndef UMAC_SUPPORT_PERIODIC_PERFSTATS
#define UMAC_SUPPORT_PERIODIC_PERFSTATS 0
#endif
#ifndef UMAC_SUPPORT_CHANUTIL_MEASUREMENT
#define UMAC_SUPPORT_CHANUTIL_MEASUREMENT 1
#endif
#ifndef ATH_GEN_RANDOMNESS
#define ATH_GEN_RANDOMNESS 0
#endif
#ifndef UMAC_SUPPORT_PROXY_ARP
#define UMAC_SUPPORT_PROXY_ARP 1
#endif
#ifndef UMAC_SUPPORT_DGAF_DISABLE
#define UMAC_SUPPORT_DGAF_DISABLE 1
#endif
#ifndef UMAC_SUPPORT_HS20_L2TIF
#define UMAC_SUPPORT_HS20_L2TIF
#endif
#ifndef ATH_SUPPORT_HS20
#define ATH_SUPPORT_HS20 1
#endif
#ifndef UMAC_SUPPORT_STA_MODE
#define UMAC_SUPPORT_STA_MODE 0
#endif
#ifndef UMAC_SUPPORT_TXDATAPATH_NODESTATS
#define UMAC_SUPPORT_TXDATAPATH_NODESTATS 1
#endif
#ifndef UMAC_SUPPORT_ACFG
#define UMAC_SUPPORT_ACFG 1
#endif
#ifndef ATH_11AC_TXCOMPACT
#define ATH_11AC_TXCOMPACT 1
#endif
#ifndef QCA_NSS_NWIFI_MODE
#define QCA_NSS_NWIFI_MODE 0
#endif
#ifndef QCA_OL_RX_BATCHMODE
#define QCA_OL_RX_BATCHMODE 1
#endif
#ifndef ATH_PERF_PWR_OFFLOAD
#define ATH_PERF_PWR_OFFLOAD 1
#endif
#ifndef ATH_SUPPORT_FW_RAM_DUMP_FOR_MIPS
#define ATH_SUPPORT_FW_RAM_DUMP_FOR_MIPS 0
#endif
#ifndef WMI_RECORDING
#define WMI_RECORDING 0
#endif
#ifndef ATH_OL_11AC_DMA_BURST
#define ATH_OL_11AC_DMA_BURST 1
#endif
#ifndef ATH_OL_11AC_MAC_AGGR_DELIM
#define ATH_OL_11AC_MAC_AGGR_DELIM 0
#endif
#ifndef ATH_HOST_RX_PHY_ERROR
#define ATH_HOST_RX_PHY_ERROR 0
#endif
#ifndef AH_NEED_TX_DATA_SWAP
#define AH_NEED_TX_DATA_SWAP 0
#endif
#ifndef AH_NEED_RX_DATA_SWAP
#define AH_NEED_RX_DATA_SWAP 0
#endif
#ifndef PERE_IP_HDR_ALIGNMENT_WAR
#define PERE_IP_HDR_ALIGNMENT_WAR 1
#endif
#ifndef ATH_SUPPORT_WRAP
#define ATH_SUPPORT_WRAP 1
#endif
#ifndef ATH_PROXY_NOACK_WAR
#define ATH_PROXY_NOACK_WAR 1
#endif
#ifndef UNIFIED_SMARTANTENNA
#define UNIFIED_SMARTANTENNA 1
#endif
#ifndef ATH_VAP_DELETE_ON_RMMOD
#define ATH_VAP_DELETE_ON_RMMOD 1
#endif
#ifndef WLAN_FEATURE_FASTPATH
#define WLAN_FEATURE_FASTPATH 1
#endif
#ifndef ATH_SUPPORT_4SS
#define ATH_SUPPORT_4SS 1
#endif
#ifndef ATH_SUPPORT_DEFERRED_NODE_CLEANUP
#define ATH_SUPPORT_DEFERRED_NODE_CLEANUP 1
#endif
#ifndef ATH_SUPPORT_KEYPLUMB_WAR
#define ATH_SUPPORT_KEYPLUMB_WAR 1
#endif
#ifndef QCA_NSS_PLATFORM
#define QCA_NSS_PLATFORM 1
#endif
#ifndef QCA_NSS_WIFI_OFFLOAD_SUPPORT
#define QCA_NSS_WIFI_OFFLOAD_SUPPORT 1
#endif
#ifndef UMAC_VOW_DEBUG
#define UMAC_VOW_DEBUG 1
#endif
#ifndef RX_DEBUG
#define RX_DEBUG 1
#endif
#ifndef DUMP_FW_RAM
#define DUMP_FW_RAM 1
#endif
#ifndef DBGLOG_WQ_BASED
#define DBGLOG_WQ_BASED 1
#endif
#ifndef HTT_RX_DESC_ALIGN_RESERVED
#define HTT_RX_DESC_ALIGN_RESERVED 0
#endif
#ifndef ATH_SUPPORT_CE_BARRIER
#define ATH_SUPPORT_CE_BARRIER 0
#endif
#ifndef LIMIT_RXBUF_LEN_4K
#define LIMIT_RXBUF_LEN_4K 1
#endif
#ifndef QCA_OL_VLAN_WAR
#define QCA_OL_VLAN_WAR 1
#endif
#ifndef AR900B_IP1_EMU_HACK
#define AR900B_IP1_EMU_HACK 0
#endif
#ifndef BEELINER_HOST_FPGA_FLAG
#define BEELINER_HOST_FPGA_FLAG 0
#endif
#ifndef IPQ4019_EMU
#define IPQ4019_EMU 0
#endif
#ifndef QCA_OL_SUPPORT_RAWMODE_TXRX
#define QCA_OL_SUPPORT_RAWMODE_TXRX 1
#endif
#ifndef QCA_OL_SUPPORT_RAWMODE_AR900B_BUFFCOALESCE
#define QCA_OL_SUPPORT_RAWMODE_AR900B_BUFFCOALESCE 1
#endif
#ifndef QCA_RAWMODE_OPTIMIZATION_CONFIG
#define QCA_RAWMODE_OPTIMIZATION_CONFIG 0
#endif
#ifndef QCA_SUPPORT_RAWMODE_PKT_SIMULATION
#define QCA_SUPPORT_RAWMODE_PKT_SIMULATION 1
#endif
#ifndef PCI_INTERRUPT_WAR_ENABLE
#define PCI_INTERRUPT_WAR_ENABLE 0
#endif
#ifndef ATH_MCAST_HOST_INSPECT
#define ATH_MCAST_HOST_INSPECT 0
#endif
#ifndef MCAST_ENHANCE_NO_CONSISTENT_MEM
#define MCAST_ENHANCE_NO_CONSISTENT_MEM 1
#endif
#ifndef ATH_SUPPORT_SPLITMAC
#define ATH_SUPPORT_SPLITMAC 1
#endif
#ifndef ATH_SUPPORT_FIPS
#define ATH_SUPPORT_FIPS 1
#endif
#ifndef ATH_SUPPORT_MGMT_TX_STATUS
#define ATH_SUPPORT_MGMT_TX_STATUS 1
#endif
#ifndef ENHANCED_STATS
#define ENHANCED_STATS 1
#endif
#ifndef PEER_CACHEING_HOST_ENABLE
#define PEER_CACHEING_HOST_ENABLE 1
#endif
#ifndef QCA_AIRTIME_FAIRNESS
#define QCA_AIRTIME_FAIRNESS 1
#endif
#ifndef QCA_LTEU_SUPPORT
#define QCA_LTEU_SUPPORT 1
#endif
#ifndef ATH_BAND_STEERING
#define ATH_BAND_STEERING 1
#endif
#ifndef ATH_SSID_STEERING
#define ATH_SSID_STEERING 1
#endif
#ifndef ATH_SUPPORT_MBO
#define ATH_SUPPORT_MBO 1
#endif
#ifndef QCA_PARTNER_DIRECTLINK
#define QCA_PARTNER_DIRECTLINK 0
#endif
#ifndef QCA_PARTNER_CBM_DIRECTPATH
#define QCA_PARTNER_CBM_DIRECTPATH 0
#endif
#ifndef ATH_SUPPORT_CODESWAP
#define ATH_SUPPORT_CODESWAP 1
#endif
#ifndef DEFAULT_BOARD_DATA
#define DEFAULT_BOARD_DATA 1
#endif
#ifndef ATH_CHANNEL_BLOCKING
#define ATH_CHANNEL_BLOCKING 1
#endif
#ifndef REMOVE_INIT_DEBUG_CODE
#define REMOVE_INIT_DEBUG_CODE 1
#endif
#ifndef FEATURE_NAPI
#define FEATURE_NAPI 1
#endif
#ifndef NAPI_YIELD_BUDGET_BASED
#define NAPI_YIELD_BUDGET_BASED 1
#endif
#ifndef ACFG_NETLINK_TX
#define ACFG_NETLINK_TX 1
#endif
#ifndef CE_HW_IDX_DEBUG
#define CE_HW_IDX_DEBUG 1
#endif
#ifndef REMOTE_PKTLOG_SUPPORT
#define REMOTE_PKTLOG_SUPPORT 1
#endif
#ifndef QCN_IE
#define QCN_IE 1
#endif
#ifndef QCN_ESP_IE
#define QCN_ESP_IE 1
#endif
#ifndef PEER_FLOW_CONTROL
#define PEER_FLOW_CONTROL 1
#endif
#ifndef PEER_FLOW_CONTROL_HOST_SCHED
#define PEER_FLOW_CONTROL_HOST_SCHED 0
#endif
#ifndef PEER_FLOW_CONTROL_DEBUG
#define PEER_FLOW_CONTROL_DEBUG 0
#endif
#ifndef PEER_FLOW_CONTROL_FORCED_MODE0
#define PEER_FLOW_CONTROL_FORCED_MODE0 0
#endif
#ifndef QCA_SUPPORT_SPECTRAL_SIMULATION
#define QCA_SUPPORT_SPECTRAL_SIMULATION 0
#endif
#ifndef ATH_SUPPORT_EXTAP_IPV6
#define ATH_SUPPORT_EXTAP_IPV6 1
#endif
#ifndef MIPS_LOW_PERF_SUPPORT
#define MIPS_LOW_PERF_SUPPORT 0
#endif
#ifndef ATH_EXTAP_IPV6_CSUM_RECHECK
#define ATH_EXTAP_IPV6_CSUM_RECHECK 1
#endif
#ifndef ATH_SUPPORT_DYNAMIC_VENDOR_IE
#define ATH_SUPPORT_DYNAMIC_VENDOR_IE 1
#endif
#ifndef ATH_SUPPORT_NAC
#define ATH_SUPPORT_NAC 1
#endif
#ifndef ATH_SUPPORT_NAC_RSSI
#define ATH_SUPPORT_NAC_RSSI 1
#endif
#ifndef CFG_MAX_CLIENTS
#define CFG_MAX_CLIENTS 124
#endif
#ifndef CFG_MAX_VAPS
#define CFG_MAX_VAPS 16
#endif
#ifndef CFG_MAX_TMPNODES
#define CFG_MAX_TMPNODES 64
#endif
#ifndef WLAN_ENABLE_ERROR_ON_WARN
#define WLAN_ENABLE_ERROR_ON_WARN 1
#endif
#ifndef MESH_MODE_SUPPORT
#define MESH_MODE_SUPPORT 1
#endif
#ifndef MESH_PEER_DYNAMIC_UPDATE
#define MESH_PEER_DYNAMIC_UPDATE 1
#endif
#ifndef WIFI_MEM_MANAGER_SUPPORT
#define WIFI_MEM_MANAGER_SUPPORT 1
#endif
#ifndef DBDC_REPEATER_SUPPORT
#define DBDC_REPEATER_SUPPORT 1
#endif
#ifndef ATH_SUPPORT_NR_SYNC
#define ATH_SUPPORT_NR_SYNC 1
#endif
#ifndef FW_CODE_SIGN
#define FW_CODE_SIGN 0
#endif
#ifndef OL_STATS_WORK_QUEUE
#define OL_STATS_WORK_QUEUE 1
#endif
#ifndef DBG_LVL_MAC_FILTERING
#define DBG_LVL_MAC_FILTERING 0
#endif
#ifndef ATH_TXQ_DRAIN_DEFERRED
#define ATH_TXQ_DRAIN_DEFERRED 0
#endif
#ifndef DYNAMIC_BEACON_SUPPORT
#define DYNAMIC_BEACON_SUPPORT 1
#endif
#ifndef CONFIG_WIN
#define CONFIG_WIN 1
#endif
#ifndef DATA_CE_SW_INDEX_NO_INLINE_UPDATE
#define DATA_CE_SW_INDEX_NO_INLINE_UPDATE 1
#endif
#ifndef PANIC_ON_BUG
#define PANIC_ON_BUG 1
#endif
#ifndef WMI_NON_TLV_SUPPORT
#define WMI_NON_TLV_SUPPORT 1
#endif
#ifndef WMI_TLV_AND_NON_TLV_SUPPORT
#define WMI_TLV_AND_NON_TLV_SUPPORT 1
#endif
#ifndef PANIC_ON_BUG
#define PANIC_ON_BUG 1
#endif
#ifndef CONFIG_ATH_PCIE_MAX_PERF
#define CONFIG_ATH_PCIE_MAX_PERF 1
#endif
#ifndef HIF_PCI
#define HIF_PCI
#endif
#ifndef ATH_DIRECT_ATTACH
#define ATH_DIRECT_ATTACH 1
#endif
#ifndef QCA_OL_TX_CACHEDHDR
#define QCA_OL_TX_CACHEDHDR 1
#endif
#ifndef ATH_TX_OVERFLOW_IND
#define ATH_TX_OVERFLOW_IND 1
#endif
#ifndef ATH_SUPPORT_11N_CHANWIDTH_SWITCH
#define ATH_SUPPORT_11N_CHANWIDTH_SWITCH 1
#endif
#ifndef ATH_NON_BEACON_AP
#define ATH_NON_BEACON_AP 1
#endif
#ifndef ATH_DATA_TX_INFO_EN
#define ATH_DATA_TX_INFO_EN 1
#endif
#ifndef WMI_INTERFACE_EVENT_LOGGING
#define WMI_INTERFACE_EVENT_LOGGING 1
#endif
#ifndef WLAN_HEADERS
#define WLAN_HEADERS 1
#endif
#ifndef SUPPORT_11N
#define SUPPORT_11N 1
#endif
#ifndef SUPPORT_VHT
#define SUPPORT_VHT 1
#endif
#ifndef CONVERGED_SW
#define CONVERGED_SW 1
#endif
#ifndef ATH_PERF_PWR_OFFLOAD
#define ATH_PERF_PWR_OFFLOAD 1
#endif
#ifndef TEMP_AGGR_CFG
#define TEMP_AGGR_CFG 1
#endif
#ifndef CONFIG_AR900B_SUPPORT
#define CONFIG_AR900B_SUPPORT
#endif
#ifndef CONFIG_11AC_SUPPORT
#define CONFIG_11AC_SUPPORT
#endif
#ifndef AR900B_HEADERS_DEF
#define AR900B_HEADERS_DEF 1
#endif
#ifndef CONFIG_AR9888_SUPPORT
#define CONFIG_AR9888_SUPPORT
#endif
#ifndef AR9888_HEADERS_DEF
#define AR9888_HEADERS_DEF 1
#endif
#ifndef IPQ4019_HEADERS_DEF
#define IPQ4019_HEADERS_DEF 1
#endif
#ifndef QCA9984_HEADERS_DEF
#define QCA9984_HEADERS_DEF 1
#endif
#ifndef QCA9888_HEADERS_DEF
#define QCA9888_HEADERS_DEF 1
#endif
#ifndef ATH_SUPPORT_MCAST2UCAST
#define ATH_SUPPORT_MCAST2UCAST
#endif
#ifndef QCA_OL_TX_CACHEDHDR
#define QCA_OL_TX_CACHEDHDR 1
#endif
#ifndef DUMP_FW_RAM
#define DUMP_FW_RAM 1
#endif
#ifndef WDI_EVENT_ENABLE
#define WDI_EVENT_ENABLE
#endif
#ifndef OL_ATH_SMART_LOGGING
#define OL_ATH_SMART_LOGGING 1
#endif
#ifndef OL_ATH_CE_DEBUG
#define OL_ATH_CE_DEBUG 1
#endif
#ifndef UMAC_SUPPORT_FILS
#define UMAC_SUPPORT_FILS 1
#endif
#ifndef ATH_DATABUS_ERROR_RESET_LOCK_3PP
#define ATH_DATABUS_ERROR_RESET_LOCK_3PP 0
#endif
#ifndef QCA_TGT_FW_IRAM_DUMP_ENABLE
#define QCA_TGT_FW_IRAM_DUMP_ENABLE 1
#endif
#ifndef ATH_POWERSAVE_WAR
#define ATH_POWERSAVE_WAR 1
#endif
#ifndef ATH_SUPPORT_PRIMARY_ALLOWED_CHAN
#define ATH_SUPPORT_PRIMARY_ALLOWED_CHAN 1
#endif
#ifndef ATH_TX99_DIAG
#define ATH_TX99_DIAG 1
#endif
#ifndef USE_PLATFORM_FRAMEWORK
#define USE_PLATFORM_FRAMEWORK
#endif
#endif
