


/* Automatically generated by glib-mkenums */

#ifndef DMAP_ENUMS_H
#define DMAP_ENUMS_H

#include <glib-object.h>

G_BEGIN_DECLS


/* enumerations from "./dacp-player.h" */
GType dacp_repeat_state_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DACP_REPEAT_STATE (dacp_repeat_state_get_type())
GType dacp_play_state_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DACP_PLAY_STATE (dacp_play_state_get_type())

/* enumerations from "./dmap-connection.h" */
GType dmap_connection_state_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DMAP_CONNECTION_STATE (dmap_connection_state_get_type())

/* enumerations from "./dmap-mdns-browser.h" */
GType dmap_mdns_browser_service_type_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DMAP_MDNS_BROWSER_SERVICE_TYPE (dmap_mdns_browser_service_type_get_type())
GType dmap_mdns_browser_transport_protocol_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DMAP_MDNS_BROWSER_TRANSPORT_PROTOCOL (dmap_mdns_browser_transport_protocol_get_type())
GType dmap_mdns_browser_error_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DMAP_MDNS_BROWSER_ERROR (dmap_mdns_browser_error_get_type())

/* enumerations from "./dmap-mdns-publisher.h" */
GType dmap_mdns_publisher_error_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DMAP_MDNS_PUBLISHER_ERROR (dmap_mdns_publisher_error_get_type())

/* enumerations from "./dmap-record.h" */
GType dmap_media_kind_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DMAP_MEDIA_KIND (dmap_media_kind_get_type())

/* enumerations from "./dmap-structure.h" */
GType dmap_type_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DMAP_TYPE (dmap_type_get_type())
G_END_DECLS

#endif /* !DMAP_ENUMS_H */



