#!/bin/sh /etc/rc.common
# Copyright (C) 2013-2014 OpenWrt.org

START=01

[ -n "$(grep "DK04" /proc/device-tree/model)" ] && model="s1300"
[ -n "$(grep "DK01" /proc/device-tree/model)" ] && model="b1300"

start() {
	[ "$model" = "s1300" -o "$model" = "b1300" ] && exit 0
	echo 1 4 1 7 >/proc/sys/kernel/printk
}

stop() {
	[ "$model" = "s1300" -o "$model" = "b1300" ] && exit 0
	echo 7 4 1 7 >/proc/sys/kernel/printk
}

