#!/bin/sh  /etc/rc.common

. /lib/functions.sh
. /lib/functions/network.sh

START=99
USE_PROCD=1
PROG=/usr/bin/gl_health

start_service()
{
	procd_open_instance
	procd_set_param command "$PROG"
	procd_close_instance

}
stop_service()
{
	#killall -9 gl_health 2>/dev/null
	kill -9 $(pgrep -f '/usr/bin/gl_health') 2>/dev/null
}
