#!/bin/sh /etc/rc.common
. /lib/functions/gl_util.sh

START=19

disable_ipv6()
{
        cat << "EOF" > "/etc/sysctl.d/99-disable-ipv6.conf"
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.lo.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
EOF
        uci set network.wan6.disabled='1' 2>/dev/null
        uci commit network
}

enable_ipv6()
{
        cat << "EOF" > "/etc/sysctl.d/99-disable-ipv6.conf"
net.ipv6.conf.all.disable_ipv6=0
net.ipv6.conf.lo.disable_ipv6=0
net.ipv6.conf.default.disable_ipv6=0
EOF

        uci set network.wan6.disabled='0' 2>/dev/null
        uci commit network
}

restart()
{
        status=$(uci get glipv6.globals.enabled 2>/dev/null)
        if [ "$status" == "1" ];then
                enable_ipv6
        else
		        disable_ipv6
        fi

        /etc/init.d/sysctl restart
        /etc/init.d/network restart
}


start()
{
        status=$(uci get glipv6.globals.enabled 2>/dev/null)
        if [ "$status" == "1" ];then
                enable_ipv6
        else
		        disable_ipv6
        fi

        /etc/init.d/sysctl restart
}

stop()
{
        disable_ipv6
        /etc/init.d/sysctl restart
        /etc/init.d/network restart
}
