#!/bin/sh  /etc/rc.common

. /lib/functions.sh
. /lib/functions/network.sh
. /lib/functions/gl_util.sh

START=99
USE_PROCD=1
PROG=/usr/bin/gltertf
product=$(get_model)

start_service()
{	
	if [ ! -d "/tmp/tertf" ];then
		mkdir -p /tmp/tertf
	else
		if [ -f "/tmp/tertf/tertfinfo_bak" ];then
			cp /tmp/tertf/tertfinfo_bak /etc/tertf/tertfinfo_bak -rf
		fi
	fi
	local enable
	enable=`uci get glconfig.traffic_control.enable 2>/dev/null`
	if [ "$enable" = 1 ];then
		killall gltraffic
		if [ "$product" = "s1300" -o "$product" = "b1300" -o "$product" = "ap1300" -o "$product" = "b2200" ];then
			/etc/init.d/qca-nss-ecm stop >/dev/null
			ethtool -K eth0 gro on >/dev/null
			ethtool -K eth1 gro on >/dev/null
		elif [ "$product" = "ar750s" -o "$product" = "x1200" ];then
			/etc/init.d/shortcut-fe stop >/dev/null
		fi
	else
		killall gltraffic 2>/dev/null
	fi
	procd_open_instance
	#procd_set_param limits core="unlimited"
	procd_set_param command "$PROG"
	procd_close_instance
}
stop_service()
{
	if [ -f "/tmp/tertf/tertfinfo_bak" ];then
		cp /tmp/tertf/tertfinfo_bak /etc/tertf/tertfinfo_bak
	fi
	enable=`uci get glconfig.traffic_control.enable 2>/dev/null`
	if [ "$enable" = 0 ];then
		cp /tmp/tertf/traffic_info_bak /etc/tertf/traffic_info_bak -rf
		rm /tmp/tertf/traffic_info* -rf
		killall gltraffic 2>/dev/null
		if [ "$product" = "s1300" -o "$product" = "b1300" -o "$product" = "ap1300" ];then
			ethtool -K eth0 gro off >/dev/null
			ethtool -K eth1 gro off >/dev/null
			/etc/init.d/qca-nss-ecm start >/dev/null
		elif [ "$product" = "ar750s" -o "$product" = "x1200" ];then
			/etc/init.d/shortcut-fe start >/dev/null
		fi
	fi
	killall -9 gltertf 2>/dev/null
	killall gltertf 2>/dev/null
	killall gltraffic 2>/dev/null
}
