#!/bin/sh /etc/rc.common
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=50

USE_PROCD=1
PROG=/usr/bin/gl_crond

start_service() {
        procd_open_instance
        procd_set_param command "$PROG"
        procd_close_instance
}
