#!/bin/sh /etc/rc.common
START=99
mount_usdk()
{
        local devpath
        local action
        if [ -f "/tmp/mount.tmp" ];then
        devpath="$(head -1 /tmp/mount.tmp)"
        action="$(tail -1 /tmp/mount.tmp)"
        env -i DEVPATH=$devpath ACTION=$action /sbin/hotplug-call block
        fi
}


fix_wireless()
{
	wifi
}

start(){
	fix_wireless
         mount_usdk
        /etc/init.d/mount_usdk disable
}
