#!/bin/sh

#This is the hidden button of AR300M

model=$(awk -F': ' '/machine/ {print tolower($NF)}' /proc/cpuinfo| cut -d- -f2-)
if [ "$model" = e750 ];then
        kill -9 $(pgrep -f "switch_queue")
        switch_queue &
else
	[ $SEEN -gt 0 ] || exit 0
	echo "$BUTTON ${ACTION}" > /dev/console
 	/usr/bin/switchaction &
fi
